os: Visual Studio 2017
version: build{build}

branches:
  only:
  - master

environment:
  SpecFlowBaseVersion: 2.2.0
  SpecFlowPackageVersion: "2.2.0-ci$(APPVEYOR_BUILD_NUMBER)"
  
cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "$(SpecFlowBaseVersion)"
  assembly_file_version: "$(SpecFlowBaseVersion)"
  assembly_informational_version: "$(SpecFlowPackageVersion)"

nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

before_build:
- cmd: dotnet restore

build:
  project: TechTalk.SpecFlow.sln
  verbosity: normal



test_script:
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.RuntimeTests\bin\Debug\net452\TechTalk.SpecFlow.RuntimeTests.dll" /TestAdapterPath:%USERPROFILE%\.nuget\packages\nunit3testadapter\3.8.0
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.GeneratorTests\bin\Debug\net452\TechTalk.SpecFlow.GeneratorTests.dll"  /TestAdapterPath:%USERPROFILE%\.nuget\packages\nunit3testadapter\3.8.0
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.Specs\bin\Debug\net452\TechTalk.SpecFlow.Specs.dll"  /TestAdapterPath:%USERPROFILE%\.nuget\packages\nunit3testadapter\3.8.0
- vstest.console /logger:Appveyor "Tests\TechTalk.SpecFlow.IntegrationTests\bin\Debug\net452\TechTalk.SpecFlow.IntegrationTests.dll"  /TestAdapterPath:%USERPROFILE%\.nuget\packages\nunit3testadapter\3.8.0

#test:
#  assemblies:
#  - TechTalk.SpecFlow.GeneratorTests.dll
#  - TechTalk.SpecFlow.RuntimeTests.dll
#  - TechTalk.SpecFlow.IntegrationTests.dll
#  - TechTalk.SpecFlow.Specs.dll

artifacts:
- path: '\Installer\NuGetPackages\bin\SpecFlow.*.nupkg'
- path: Installer\SpecFlowBinPackage\bin\SpecFlowBinPackage.zip
- path: Installer\SpecFlowBinPackage\bin\SpecFlowSymbolPackage.zip