os: Visual Studio 2017
version: build{build}

image: Visual Studio 2017

branches:
  only:
  - master
  - /DotNetCore.*/
  
nuget:
  project_feed: true
  disable_publish_on_pr: true

configuration: Debug

install:
- cmd: git submodule update --init --recursive

build_script:
- cmd: msbuild /restore /bl TechTalk.SpecFlow.sln


test:
  # only assemblies to test
  assemblies:
    only:
      - '**\TechTalk.SpecFlow.RuntimeTests.dll'
      - '**\TechTalk.SpecFlow.GeneratorTests.dll'
      - '**\TechTalk.SpecFlow.Specs.dll'

artifacts:
- path: '\Installer\NuGetPackages\bin\SpecFlow.*.nupkg'
