version: 2.0.0-ci{build}
branches:
  only:
  - v2
environment:
  SpecFlowPackageVersion: "{version}"
  SpecFlowPackageVersion2: "test {APPVEYOR_BUILD_VERSION}"
  SpecFlowPackageVersion3: "test $(APPVEYOR_BUILD_VERSION)"
nuget:
#  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: >-
	$test0 = (Get-ChildItem Env:APPVEYOR_BUILD_VERSION).Value
	$test1 = (Get-ChildItem Env:SpecFlowPackageVersion).Value
	$test2 = (Get-ChildItem Env:SpecFlowPackageVersion2).Value
	$test3 = (Get-ChildItem Env:SpecFlowPackageVersion3).Value

	Write-Host "Test0: $test0"
	Write-Host "Test1: $test1"
	Write-Host "Test2: $test2"
	Write-Host "Test3: $test3"

    nuget restore
build:
  project: TechTalk.SpecFlow.sln
  verbosity: minimal
#test:
#  assemblies:
#  - TechTalk.SpecFlow.GeneratorTests.dll
#  - TechTalk.SpecFlow.RuntimeTests.dll
#  - '*UtilsTests.dll'
#  - TechTalk.SpecFlow.IntegrationTests.dll
#  - TechTalk.SpecFlow.Specs\bin\Debug\TechTalk.SpecFlow.Specs.dll
artifacts:
- path: '\Installer\NuGetPackages\bin\SpecFlow.*.nupkg'
- path: Installer\NuGetPackages\bin\SpecFlow.CustomPlugin.*.nupkg
- path: Installer\NuGetPackages\bin\SpecFlow.NUnit.1.1.1.nupkg
- path: Installer\NuGetPackages\bin\SpecFlow.NUnit.Runners.1.0.0.nupkg
- path: Installer\NuGetPackages\bin\SpecFlow.xUnit.1.0.2.nupkg